# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false
before_install:
  - Rscript -e 'install.packages("dplyr", lib="/home/travis/R-bin/lib/R/library/")'
  - Rscript -e 'install.packages("purrr", lib="/home/travis/R-bin/lib/R/library/")'
  - Rscript -e 'install.packages("readr", lib="/home/travis/R-bin/lib/R/library/")'
install:
  - Rscript -e "0" --args --bootstrap-packrat
#cache:
#  directories: $TRAVIS_BUILD_DIR/packrat/
#  packages: true
